### ISSUE TITLE
Cant download datasets

### ISSUE THREAD

**Issue by firesgc** [UPC-ViRVIG/MMVR#1]
Hello!

Do you have a schedule yet for when you will upload the datasets? 
At the moment all links are invalid (https://github.com/UPC-ViRVIG/MMVR/blob/main 404)
Your project looks great, I can't wait to test it myself.

Thank you so much!

**Comment by JLPM22** [comment]
Hello!

Thank you for your interest in the project!
I updated all links and now the data should be available to download through Google Drive.
