### ISSUE TITLE
How to change the player's self-avatar model?

### ISSUE THREAD

**Issue by Timkeeper2018** [UPC-ViRVIG/MMVR#10]
I saw that in the paper you gave a code for loading BVH animation, but is it a possible operation if I want to replace the character model? I've tried swapping before, but the movement gap between the character models was too big.

**Comment by JLPM22** [comment]
It should be possible as long as the new character model is also imported as humanoid in Unity. The idea is that Motion Matching is running using the BVH's skeleton, but then the class MotionMatchingSkinnedMeshRenderer will handle the retargeting to Unity's humanoid system. Maybe there is some problem in the retargeting process, there are some public fields that should be adjusted depending on the model. I would need more details to try to understand the problem

**Comment by Timkeeper2018** [comment]
That is what i need,thanks a lot
