### ISSUE TITLE
No Models in MMDate.zip

### ISSUE THREAD

**Issue by Timkeeper2018** [UPC-ViRVIG/MMVR#7]
It looks like you don't have "Models" in the MMDate.zip you provided, does that make a difference?

**Comment by JLPM22** [comment]
Hello! It is ok. The model is already included on the GitHub repository when cloning the project.

**Comment by Timkeeper2018** [comment]
I'm having trouble with Quick Start.
The steps are all according to Quick Start, importing finalIK
But the following error occurred, which caused the character to stand still and only the hands and head could move. Do you know why?
![test](https://user-images.githubusercontent.com/45630803/234149125-c89ed03f-2c31-4191-aefc-7a95e36430b1.jpg)
