### ISSUE TITLE
Problem with quick start

### ISSUE THREAD

**Issue by Timkeeper2018** [UPC-ViRVIG/MMVR#8]
The problem occurs when I build using the steps shown in Quick Start. The error is shown in the figure below. After I import into FinalIK, only the head and hands move after clicking the play button, the legs are fixed, and the camera is detached from the head when I move my body.
I tried to build the project under windows and build the project under the Android environment, the result is the same, what did I do wrong? The unity version is 2021-2-13f1.
![test](https://user-images.githubusercontent.com/45630803/234157603-204c8fa6-5359-469e-be97-0d08b00ad1d1.jpg)
![test2](https://user-images.githubusercontent.com/45630803/234157794-23fa8ca4-cac9-4c79-bdc2-393d131a597c.jpg)

**Comment by JLPM22** [comment]
Hello,

I reproduced the error when deleting the MMData/Data folder. It looks like this error appears when the script cannot find the databases. 
I understand you downloaded the processed database from [here](https://zenodo.org/record/7048601/files/MMData.zip?download=1) and uncompressed it in the MMData folder. Please, repeat the procedure or make sure the folders are correctly placed as follows:
The MMData folder should look like this:
![image](https://user-images.githubusercontent.com/45894435/234217697-3905020d-0f8c-4186-bb1c-5be6baa1e427.png)
The MMData/Animations folder:
![image](https://user-images.githubusercontent.com/45894435/234218347-35ba1a4a-ea61-4ce3-9f41-6643f84ae134.png)
And  the MMData/Data folder:
![image](https://user-images.githubusercontent.com/45894435/234218437-960302bf-4425-4412-8f0f-15d4f22f6241.png)

It should work with the Windows build in the Unity editor with the Meta Quest connected through Link or Air Link.

If there are any other errors in the Unity Console let me know, they may help to solve the issue. Maybe it is related to the paths, but as long as MMData folder is in the root of the project (Assets/MMData/...) it should be fine.

**Comment by Timkeeper2018** [comment]
I seem to have forgotten to copy some files, thank you for your answer. This is an inspiring work
